version: '3.9'
name: 'lidars'

services:
  # Global planner service
  lidar1:
    image: lalayants/for-drones-lidar
    container_name: lidar1
    command: ["/bin/bash", "-ci", ""]
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
      - ./:/workspace/ros_ws/

